jobs:
- name: riemann-boshrelease
  plan:
  - aggregate:
    - get: release-git-repo
      trigger: true
    - get: pipeline-tasks
    - get: final-builds-dir-tarball
    - get: releases-dir-tarball
  - task: finalize-release
    file: pipeline-tasks/finalize-bosh-release.yml
    tags: [iaas]
    config:
      params:
        PRIVATE_YML_CONTENT: {{private-yml}}
  - aggregate:
    - put: release-tarball
      tags: [iaas]
      params:
        file: finalized-release/riemann-*.tgz
    - put: final-builds-dir-tarball
      tags: [iaas]
      params:
        file: finalized-release/final-builds-dir-riemann.tgz
    - put: releases-dir-tarball
      tags: [iaas]
      params:
        file: finalized-release/releases-dir-riemann.tgz

resources:
- name: release-git-repo
  type: git
  source:
    uri: {{release-git-url}}
    branch: {{release-git-branch}}
- name: pipeline-tasks
  type: git
  source:
    uri: {{pipeline-tasks-git-url}}
    branch: {{pipeline-tasks-git-branch}}
- name: release-tarball
  type: s3-iam
  source:
    bucket: {{s3-bosh-releases-bucket}}
    regexp: riemann-(.*).tgz
    region_name: {{s3-bosh-releases-region}}
    server_side_encryption: AES256
- name: final-builds-dir-tarball
  type: s3-iam
  source:
    bucket: {{s3-bosh-releases-bucket}}
    versioned_file: final-builds-dir-riemann.tgz
    region_name: {{s3-bosh-releases-region}}
    server_side_encryption: AES256
- name: releases-dir-tarball
  type: s3-iam
  source:
    bucket: {{s3-bosh-releases-bucket}}
    versioned_file: releases-dir-riemann.tgz
    region_name: {{s3-bosh-releases-region}}
    server_side_encryption: AES256

resource_types:
- name: s3-iam
  type: docker-image
  source:
    repository: 18fgsa/s3-resource
